[server]
headless = true
address = "0.0.0.0"
port = 5000
maxUploadSize = 10
maxMessageSize = 50
fileWatcherType = "none"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"